### ISSUE TITLE
Collaboration on mikuVU 

### ISSUE THREAD

**Issue by Null-39** [EK720/MikuVU#1]
Hi I am the guy who made mikuVU. Are you in the henkaku discord or have a way we can communicate easily to collaborate on this?

**Comment by Null-39** [comment]
There's a few things I've had in mind that I always wanted to implement but never could get to work properly. 

-smooth fade transitions between images that utilize alpha channel so it's not a harsh slideshow 
-offline mode that instead of giving the network error message will display previously downloaded images from the "/SAVED/" folder if any are available so the application can retain functionality when there's no connection. Obviously there would still need to be some form of error handling for when no images are in the folder and there's no WiFi. Idk I never had it working properly and just kinda started working on other stuff. Seeing your comment on the Internet archive has got me thinking about it again. :)

**Comment by EK720** [comment]
Hi @Null-39! I saw you follow my repository and figured you were the original creator. In any case, welcome!

Fade seems really tough using the barebones built-in graphics library, but _maybe_ it's doable.

Offline mode should be pretty easy, except for the fact i

**Comment by EK720** [comment]
Also, let me know your Discord username if you still want to get in touch about this update.
If not, chatting on GitHub like this is more than OK with me :)

**Comment by Null-39** [comment]
My discord is "null.39"

**Comment by EK720** [comment]
All features mentioned in this issue have been added. Closing the issue for now.
